language: ruby
os:
  - linux
  - osx
osx_image: xcode7.2
env:
  - USE_ATLAS=1       # This configuration installs ATLAS, builds and tests the nmatrix, nmatrix-atlas, and nmatrix-lapacke gems
  - USE_OPENBLAS=1    # Installs OpenBLAS and reference LAPACK, builds and tests nmatrix, nmatrix-lapacke
  - USE_REF=1         # Installs OpenBLAS and reference LAPACK, builds and tests nmatrix, nmatrix-lapacke
  - NO_EXTERNAL_LIB=1 # No external libraries installed, only nmatrix
rvm:
  - 2.0.0-p648
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - 2.4.2
  - ruby-head
  - 2.3.0-clang
  - ruby-head-clang
  # JRuby versions --- experimental, pending merging Prasun's GSoC project.
  - jruby-9.0.5.0 # earliest supported version (uncomment when jruby-head is passing)
  - jruby-head    # latest supported JRuby
  # Make sure to add exclude lines for new JRuby versions below.

before_install: ./travis.sh before_install

install: ./travis.sh install

script: ./travis.sh script

matrix:
  include:
    - os: osx
      compiler: clang
      rvm: 2.2
      env:
        - ruby_version=2.4.0-dev USE_OPENBLAS=1
    - os: osx
      compiler: clang
      rvm: 2.2
      env:
        - ruby_version=2.1.8 USE_OPENBLAS=1
